# config.yaml
experiment_name: quadrotor_training
timestamp: null  # 自动生成，无需填写

# Env Setting
env:
  type: QuadFlyEnv  # 环境类名
  parameters: {}  # 环境初始化参数（如需要）

# RLAgent Setting
agent:
  type: SACAgent  # 算法类名
  parameters:
    state_dim: null  # 自动从环境获取
    action_dim: null  # 自动从环境获取
    memo_capacity: 10000
    lr_actor: 0.0003
    lr_critic: 0.0003
    gamma: 0.99
    tau: 0.005
    layer1_dim: 256
    layer2_dim: 256
    batch_size: 256

# 训练配置
training:
  episode_num: 20000
  step_num: 200
  visualize_interval: 10000
  save_episode_plots: True
  plot_reward: True
  save_best_model: False
  window_size: 20  # 滑动窗口大小

# 可视化配置
visualizer:
  type: EpisodeVisualizer  # 可视化器类名
  parameters:
    step_interval: null  # 动态计算，无需填写

# 路径配置
paths:
  model_dir: ./models/
  episode_plot_dir: ./episode_plots/
  training_plot_dir: ./training_plots/